"""fixing errors

Revision ID: 20bc32725eac
Revises: bc5cd97efc64
Create Date: 2024-07-15 16:15:12.248532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bc32725eac'
down_revision = 'bc5cd97efc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    with op.batch_alter_table('task_tags', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='fk_comments_project_id_project'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='fk_comments_task_id_task'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comments_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_comments')
    )
    # ### end Alembic commands ###
