"""comment migration.

Revision ID: bc5cd97efc64
Revises: 
Create Date: 2024-07-15 00:56:01.419030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5cd97efc64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
